Vagrant.configure("2") do |config|
	config.ssh.insert_key = false
	config.vm.define "web_server" do |webserver|
		webserver.vm.box = "centos/7"
		webserver.vm.network "forwarded_port", guest: 80, host: 8180
		webserver.vm.network "forwarded_port", guest:443, host: 8443
		config.vm.network "private_network", ip: "192.168.10.5"
		config.vm.hostname = "web-server"
		config.vm.network "public_network"
                #Here you can add a provisoner and provider
	end	

	config.vm.define "app_server" do |application_server|
		application_server.vm.box = "centos/7"
		application_server.vm.network "forwarded_port", guest: 7001, host: 7001
		config.vm.network "private_network", ip: "192.168.10.6"
		config.vm.hostname = "app-server"
		config.vm.network "public_network"
	end

	config.vm.define "db_server" do |db_server|
		db_server.vm.box = "centos/7"
		config.vm.network "private_network", ip: "192.168.10.7"
		config.vm.hostname = "mydb"
		config.vm.network "public_network"
	end	
end
